name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install -g pnpm &&
          pnpm install &&
          npx playwright install &&
          composer install &&
          curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | sudo -E bash &&
          sudo apt install symfony-cli

      - name: testCommand
        run: pnpm run test