name: Playwright Tests
on:
  pull_request:
    branches: [main]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
  BASE_URL: ${{ secrets.BASE_URL }}

  # specific to this workflow :
  NODE_ENV: "test"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.12

      - uses: actions/setup-node@v3
        with:
          node-version: 20.3.1

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps

      - name: build the application 
        run: pnpm run build

      - name: starts the application in production mode
        run: pnpm run start &

      - name: Run Playwright tests
        run: pnpx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30